catch err {
    panic("error")
}

println("error:", err)
